---
- name: check that the build exists
  stat:
    path: "{{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine/build"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_build

- name: clone gosts 
  ansible.builtin.git:
    repo: 'https://github.com/gost-engine/engine.git'
    dest: "{{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine"
    version: openssl_1_1_1
  when: not check_build.stat.exists

- name: create build directory
  file: path="{{ ansible_user_dir }}"/node/node-ml/crypto/ffi/engine/build/ state=directory 
  when: not check_build.stat.exists
      
- name: make gosts
  command: 
    cmd: /snap/bin/cmake -DCMAKE_BUILD_TYPE=Release {{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine
    chdir: "{{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine/build"

- name: config gosts
  command: 
    cmd: /snap/bin/cmake --build . --config Release
    chdir: "{{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine/build"

- name: install gosts
  command: 
    cmd: /snap/bin/cmake --build . --target install --config Release
    chdir: "{{ ansible_user_dir }}/node/node-ml/crypto/ffi/engine/build"