---
# Control docker containers
- name: up docker containers
  command:
    cmd: docker-compose -p node up -d
    chdir: "/home/{{ ansible_user_id }}/node/"
  when: mode != "down" and mode != "clean"

- name: stop docker containers
  command:
    cmd: docker-compose -p node stop
    chdir: "/home/{{ ansible_user_id }}/node/"
  when: mode == "down"

- name: down docker containers
  command:
    cmd: docker-compose -p node down
    chdir: "/home/{{ ansible_user_id }}/node/"
  when: mode == "down" 
