- hosts: control_node
    
    environment:
      SSL_CERT_DIR: /etc/ssl/certs

  tasks:

  - name: check that the docker and docker-compose exists
    stat:
      path: "{{ item }}"
      get_attributes: no
      get_checksum: no
      get_mime: no
    with_items:
       - /usr/bin/docker
       - /usr/local/bin/docker-compose
    register: check_docker

  - name: Added tasks for installing docker
    include_role: 
       name: docker 
    when: not (check_docker.results[0].stat.exists and check_docker.results[1].stat.exists)
    tags: 
      - initial_run

  roles:
    - common
    - build_control_single_docker
  tags:
    - initial_run
    - start
    - rebuild
    - stop
    - down
    - up
    