---
- hosts: control_node
  gather_facts: no

  tasks:
  - setup:
      filter: ansible_user*
        
  - name: generate ssh key
    command: ssh-keygen -t rsa -f "$HOME/.ssh/id_rsa" -P ""

  - name: ssh-copy-id
    command: "sshpass -p {{ hostvars[item]['ansible_become_pass'] }} ssh-copy-id -i /home/{{ ansible_user_id }}/.ssh/id_rsa.pub -o StrictHostKeyChecking=no {{ hostvars[item]['ansible_user'] }}@{{ item }}"
    with_items:
      - "{{ groups['managed_nodes'] }}"


- hosts: all
  roles:
    - predeploy
    - common
    - gosts
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
  tags: 
  - install_nodes
      
 
- hosts: control_node
  gather_facts: no
  tasks:
  - setup:
      filter: ansible_user*     
  roles:
       - build_control_node
  environment:
      SSL_CERT_DIR: /etc/ssl/certs
  tags:
  - build_control



- hosts: managed_nodes
  roles:
    - build_managed
  tags:
  - build_managed

    
      
