---
- hosts: control_node
  gather_facts: no
  - setup:
         filter: ansible_user*

  roles:
    - predeploy
    - common
    - build_control_docker
        
- hosts: managed_nodes
  vars:
    mode: "up"
    pipes:
    - apiin
    - apiout
    - broadcast

  tasks:
  - name: check that the docker and docker-compose exists
    stat:
      path: "{{ item }}"
      get_attributes: no
      get_checksum: no
      get_mime: no
    with_items:
      - /usr/bin/docker
      - /usr/local/bin/docker-compose
    register: check_docker

  - name: Install docker on hosts 
      include_roles: 
        name: docker
      when: not (check_docker.results[0].stat.exists and check_docker.results[1].stat.exists)
 
  roles:
     - build_managed_docker
  tags:
   - up
   - rebuild
   - initial_run
   - reload_api 
   - start
   - down
   - stop  
      