FROM ubuntu

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/Moscow" DOPENSSL_ENGINES_DIR="/usr/lib/ssl"

WORKDIR /root
COPY node/node-ml/crypto/ffi/ node/node-ml/crypto/ffi/
RUN apt-get update
RUN apt-get install -y liblz4-dev \
                    libbz2-dev \
                    zlib1g-dev \
                    libsnappy-dev \
                    libjemalloc-dev \
                    openssl \
                    libssl-dev \
                    cmake \
                    git \
                    curl
RUN ln -s /usr/lib/x86_64-linux-gnu/libjemalloc.so.2 /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
RUN curl -vLJO https://github.com/CakeML/cakeml/releases/download/v1469/cake-x64-64.tar.gz
RUN tar -xvf cake-x64-64.tar.gz
WORKDIR ./cake-x64-64
RUN make
WORKDIR ../node/node-ml/crypto/ffi/engine/build
RUN rm -rf ./*
RUN cmake .. -DOPENSSL_ENGINES_DIR="/usr/lib/ssl"
RUN cmake --build . --config Release
RUN cmake --build . --target install --config Release
WORKDIR ../../../../
RUN mkdir -p storage/dbstore
RUN git clone https://github.com/vishnubob/wait-for-it.git
ENTRYPOINT wait-for-it/./wait-for-it.sh 10.1.10.22:8000 -- ./Main.cake --fgenesis=test-node/genesis --fkeypair=test-node/keypair --fnodesinfo=test-node/nodes --max-block-size=10 --apiin=apiin --apiout=apiout