---
- hosts: control_node
  vars:
      ip_nodes:
      - 192.168.2.3

  tasks:
  
  - name: generate ssh key
    command: ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -P ""

  - name: ssh-copy-id
    command: ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@"{{ item }}"
    become: yes
    with_items: "{{ ip_nodes }}"
    tags: ssh_copy