---
- name: install prerequirements 
  apt: 
    name: "{{ item }}"
  with_items:
  - openssl
  - liblz4-dev
  - libbz2-dev
  - zlib1g-dev
  - libsnappy-dev
  - libjemalloc-dev
  - libzstd-dev
  - virtualenv
  - make
  - build-essential
  - libssl-dev
  - pkg-config
  - git
  - python3-pip
  - snapd

- name: install cmake 3.18
  community.general.snap:
    name: cmake
    classic: yes
