---
- name: create remote path
  file: path=/home/{{ ansible_user_id }}/node/node-ml/test-node/ state=directory 

- name: copy Main.cake
  copy:
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/Main.cake"
    dest: "/home/{{ ansible_user_id }}/node/node-ml/Main.cake"
    mode: ug+x

- name: copy GenesisGenerator
  copy:
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/genesis-generator/GenesisGenerator"
    dest: "/home/{{ ansible_user_id }}/node/node-ml/GenesisGenerator"
    mode: ug+x

- name: copy params
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/test-node/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/node/node-ml/test-node/"
  with_items:
  - genesis
  - keypair
  - nodes

- name: copy node_info
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node_info"
    dest: "/home/{{ ansible_user_id }}/node/"

- name: check that the node-ml-api exists
  stat:
    path: "/home/{{ ansible_user_id }}/node/node-ml-api"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_api

- name: copy api
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml-api"
    dest: "/home/{{ ansible_user_id }}/node/"
    mode: preserve
    directory_mode: ug+rw
  when: not check_api.stat.exists

- name: delete old node.log files
  file: 
    path: "/home/{{ ansible_user_id }}/node/node-ml/node.log" 
    state: absent
  when: mode != "down"

- name: create node.log files
  file: 
    path: "/home/{{ ansible_user_id }}/node/node-ml/node.log" 
    state: touch
    mode: ugo+rw
  when: mode != "down"

- name: template api-pipe-settings
  ansible.builtin.template:
    src: "./templates/api-pipe-settings-docker.j2"
    dest: "/home/{{ ansible_user_id }}/node/pipe-settings.py"

- name: template api-settings
  ansible.builtin.template:
    src: "./templates/api-settings.j2"
    dest: "/home/{{ ansible_user_id }}/node/api-settings.py"

- name: template loki-config.j2
  ansible.builtin.template:
    src: "./templates/loki-config.j2"
    dest: "/home/{{ ansible_user_id }}/node/local-config.yaml"

- name: template grafana.j2
  ansible.builtin.template:
    src: "./templates/grafana.j2"
    dest: "/home/{{ ansible_user_id }}/node/grafana.ini"

- name: template docker-compose
  ansible.builtin.template:
    src: "./templates/docker-compose.j2"
    dest: "/home/{{ ansible_user_id }}/node/docker-compose.yml"
