---
- name: create remote path
  file: path="{{ ansible_user_dir }}/node/node-ml/test-node/ state=directory"

- name: copy Main.cake
  copy:
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/Main.cake"
    dest: "{{ ansible_user_dir }}/node/node-ml/Main.cake"
    mode: ug+x

- name: copy GenesisGenerator
  copy:
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/genesis-generator/GenesisGenerator"
    dest: "{{ ansible_user_dir }}/node/node-ml/GenesisGenerator"
    mode: ug+x

- name: copy params
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml/test-node/{{ item }}"
    dest: "{{ ansible_user_dir }}/node/node-ml/test-node/"
  with_items:
  - genesis
  - keypair
  - nodes

- name: copy node_info
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node_info"
    dest: "{{ ansible_user_dir }}/node/"

- name: check that the node-ml-api exists
  stat:
    path: "{{ ansible_user_dir }}/node/node-ml-api"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_api

- name: copy api
  copy: 
    src: "{{ hostvars.localhost.ansible_facts.user_dir }}/node/node-ml-api"
    dest: "{{ ansible_user_dir }}/node/"
    mode: preserve
    directory_mode: ug+rw
  when: not check_api.stat.exists

- name: delete old node.log files
  file: 
    path: "{{ ansible_user_dir }}/node/node-ml/node.log" 
    state: absent
  when: mode != "down"

- name: create node.log files
  file: 
    path: "{{ ansible_user_dir }}/node/node-ml/node.log" 
    state: touch
    mode: ugo+rw
  when: mode != "down"

- name: template api-pipe-settings
  ansible.builtin.template:
    src: "api-pipe-settings-docker.j2"
    dest: "{{ ansible_user_dir }}/node/pipe-settings.py"

- name: template api-settings
  ansible.builtin.template:
    src: "api-settings.j2"
    dest: "{{ ansible_user_dir }}/node/api-settings.py"

- name: template loki-config.j2
  ansible.builtin.template:
    src: "loki-config.j2"
    dest: "{{ ansible_user_dir }}/node/local-config.yaml"

- name: template grafana.j2
  ansible.builtin.template:
    src: "grafana.j2"
    dest: "{{ ansible_user_dir }}/node/grafana.ini"

- name: template docker-compose
  ansible.builtin.template:
    src: "docker-compose.j2"
    dest: "{{ ansible_user_dir }}/node/docker-compose.yml"

- name: up docker containers
  command:
    cmd: docker-compose -p node up -d
    chdir: "{{ ansible_user_dir }}/node/"
  tags:
  - up
  - rebuild
  - initial_run
  - reload_api

- name: start docker containers
  command:
    cmd: docker-compose -p node start
    chdir: "{{ ansible_user_dir }}/node/"
  tags:
  - start

- name: stop docker containers
  command:
    cmd: docker-compose -p node stop
    chdir: "{{ ansible_user_dir }}/node/"
  tags:
  - down
  - stop

- name: down docker containers
  command:
    cmd: docker-compose -p node down
    chdir: "{{ ansible_user_dir }}/node/"
  tags:
  - down
