---

- name: check that the node exists
  stat:
    path: "{{ ansible_user_dir }}/node/"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_node

- name: Create node directory
  file:
    path: "{{ ansible_user_dir }}/node/"
    state: directory
  when: not check_node.stat.exists

- name: check that the node-ml exists
  stat:
    path: "{{ ansible_user_dir }}/node/node-ml"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_node_ml

- name: Create node-ml directory
  file:
    path: "{{ ansible_user_dir }}/node/node-ml/"
    state: directory
  when: not check_node_ml.stat.exists

- name: clone node-ml
  git:
    repo: 'https://gitlab.com/InnoChain/node-ml.git'
    dest: "{{ ansible_user_dir }}/node/node-ml"
  when: not check_node_ml.stat.exists

- name: check that the node-ml-api exists
  stat:
    path: "{{ ansible_user_dir }}/node/node-ml-api"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: check_node_ml_api

- name: Create node-ml-api directory
  file:
    path: "{{ ansible_user_dir }}/node/node-ml-api/"
    state: directory
  when: not check_node_ml_api.stat.exists
  
- name: clone node-ml-api
  git:
    repo: 'https://gitlab.com/RIRussel/node-ml-api.git'
    dest: {{ ansible_user_dir }}/node/node-ml-api
  when: not check_node_ml_api.stat.exists
